In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

sns.set()
%matplotlib inline

In [3]:
data = pd.read_csv('Datasets/365Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
x = data.iloc[:,:2]
y = data.iloc[:, 2]

In [5]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [6]:
x_scaled = scaler.transform(x)

In [7]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [8]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [9]:
reg.intercept_

3.330238095238095

In [12]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [13]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### Making Predictions with the Standardized Coefficients (Weights)

In [15]:
new_data = pd.DataFrame(data = [[1700, 2], [1800, 1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [16]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [17]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [18]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [19]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:, 0].reshape(-1,1)
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [21]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])