In [1]:
import numpy as np

In [2]:
keep_probs = 0.8
a3 = np.random.randn(3,4)
d3 = np.random.rand(a3.shape[0], a3.shape[1]) < keep_probs

In [3]:
a3

array([[-2.35393271, -0.49464664,  0.73127101, -0.73339368],
       [-0.574875  , -1.30448703,  0.93654332,  1.31925603],
       [ 1.90392108, -0.76782477, -0.13190367,  0.92870401]])

In [4]:
d3

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [5]:
a3 = np.multiply(a3, d3)

In [6]:
a3

array([[-2.35393271, -0.49464664,  0.73127101, -0.73339368],
       [-0.        , -1.30448703,  0.93654332,  1.31925603],
       [ 1.90392108, -0.76782477, -0.        ,  0.        ]])

In [7]:
a3 /= keep_probs

In [8]:
a3

array([[-2.94241589, -0.61830829,  0.91408876, -0.9167421 ],
       [-0.        , -1.63060879,  1.17067915,  1.64907004],
       [ 2.37990135, -0.95978096, -0.        ,  0.        ]])