In [1]:
import math
import numpy as np
import h5py
import tensorflow as tf
from tensorflow.python.framework import ops

In [2]:
def load_dataset():
    train_dataset = h5py.File('datasets/train_signs.h5', 'r')
    train_set_x_orig = np.array(train_dataset['train_set_x'][:]) # Train Set Features
    train_set_y_orig = np.array(train_dataset['train_set_y'][:]) # Train Set Labels
    
    test_dataset = h5py.File('datasets/test_signs.h5', 'r')
    test_set_x_orig = np.array(test_dataset['test_set_x'][:]) # Test Set Features
    test_set_y_orig = np.array(test_dataset['test_set_y'][:]) # Test Set Labels
    
    classes = np.array(test_dataset['list_classes'][:]) # The List of Classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

In [3]:
tf.__version__

'2.1.0'

In [4]:
# Tensorflow Basics
# Defining Tensors in TensorFlow

# 0D Tensor
d0 = tf.ones((1,))

# 1D Tensor
d1 = tf.ones((2,))


# 2D Tensor
d2 = tf.ones((2,2))


# 3D Tensor
d3 = tf.ones((2,2,2))


In [5]:
print(d0.numpy())

[1.]


In [6]:
print(d1.numpy())

[1. 1.]


In [7]:
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [8]:
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [9]:
# Defining Constants in Tensorflow
# A Constant is the simplest category of tensor
# Not Trainable
# Can have any dimension

# Define a 2*3 Constant:
a = tf.constant(3, shape=[2,3])

# Define a 2*2 Constant:
b = tf.constant([1,2,3,4], shape=[2,2])

In [10]:
print(a.numpy())

[[3 3 3]
 [3 3 3]]


In [11]:
print(b.numpy())

[[1 2]
 [3 4]]


In [12]:
# Define a Variable
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
a1 = tf.Variable([1,2,3,4,5,6], dtype=tf.int16)

In [13]:
print(a0.numpy())

[1. 2. 3. 4. 5. 6.]


In [14]:
print(a1.numpy())

[1 2 3 4 5 6]


In [15]:
# Define a Constant
b = tf.constant(2, tf.float32)

In [16]:
# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0*b

In [17]:
print(c0)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


In [18]:
print(c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


In [19]:
A = tf.ones([2,3,4])

In [20]:
A.numpy()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [21]:
tf.reduce_sum(A, 0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>

In [22]:
tf.reduce_sum(A,1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>

In [23]:
tf.reduce_sum(A,2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [24]:
import tensorflow as tf

In [25]:
print(tf.version)

<module 'tensorflow_core._api.v2.version' from 'F:\\DO_NOT_TOUCH\\Anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\version\\__init__.py'>


In [26]:
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [27]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"], ["Test", "Yes"]], tf.string)

In [28]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [29]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [30]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [31]:
rank2_tensor.shape

TensorShape([2, 2])

In [32]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones

In [33]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [34]:
tensor2 = tf.reshape(tensor1, [2,3,1])

In [35]:
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [36]:
tensor3 = tf.reshape(tensor2, [3,-1])

In [37]:
tensor3.shape

TensorShape([3, 2])

In [39]:
from tensorflow import keras

In [40]:
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

In [41]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [42]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

In [43]:
model.fit(xs, ys, epochs=500)

Train on 6 samples
Epoch 1/500
6/6 [==============================] - 1s 193ms/sample - loss: 38.1441
Epoch 2/500
6/6 [==============================] - 0s 5ms/sample - loss: 30.3573
Epoch 3/500
6/6 [==============================] - 0s 1000us/sample - loss: 24.2239
Epoch 4/500
6/6 [==============================] - 0s 497us/sample - loss: 19.3915
Epoch 5/500
6/6 [==============================] - 0s 336us/sample - loss: 15.5827
Epoch 6/500
6/6 [==============================] - 0s 330us/sample - loss: 12.5794
Epoch 7/500
6/6 [==============================] - 0s 500us/sample - loss: 10.2100
Epoch 8/500
6/6 [==============================] - 0s 503us/sample - loss: 8.3394
Epoch 9/500
6/6 [==============================] - 0s 332us/sample - loss: 6.8614
Epoch 10/500
6/6 [==============================] - 0s 500us/sample - loss: 5.6925
Epoch 11/500
6/6 [==============================] - 0s 166us/sample - loss: 4.7668
Epoch 12/500
6/6 [==============================] - 0s 333us/sample - l

Epoch 100/500
6/6 [==============================] - 0s 165us/sample - loss: 0.2310
Epoch 101/500
6/6 [==============================] - 0s 169us/sample - loss: 0.2262
Epoch 102/500
6/6 [==============================] - 0s 167us/sample - loss: 0.2216
Epoch 103/500
6/6 [==============================] - 0s 0s/sample - loss: 0.2170
Epoch 104/500
6/6 [==============================] - 0s 167us/sample - loss: 0.2126
Epoch 105/500
6/6 [==============================] - 0s 170us/sample - loss: 0.2082
Epoch 106/500
6/6 [==============================] - 0s 167us/sample - loss: 0.2039
Epoch 107/500
6/6 [==============================] - 0s 168us/sample - loss: 0.1997
Epoch 108/500
6/6 [==============================] - 0s 166us/sample - loss: 0.1956
Epoch 109/500
6/6 [==============================] - 0s 166us/sample - loss: 0.1916
Epoch 110/500
6/6 [==============================] - 0s 167us/sample - loss: 0.1877
Epoch 111/500
6/6 [==============================] - 0s 167us/sample - loss: 0.

Epoch 198/500
6/6 [==============================] - 0s 165us/sample - loss: 0.0302
Epoch 199/500
6/6 [==============================] - 0s 169us/sample - loss: 0.0296
Epoch 200/500
6/6 [==============================] - 0s 0s/sample - loss: 0.0290
Epoch 201/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0284
Epoch 202/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0278
Epoch 203/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0272
Epoch 204/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0267
Epoch 205/500
6/6 [==============================] - 0s 0s/sample - loss: 0.0261
Epoch 206/500
6/6 [==============================] - 0s 164us/sample - loss: 0.0256
Epoch 207/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0251
Epoch 208/500
6/6 [==============================] - 0s 333us/sample - loss: 0.0246
Epoch 209/500
6/6 [==============================] - 0s 333us/sample - loss: 0.024

Epoch 296/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0040
Epoch 297/500
6/6 [==============================] - 0s 164us/sample - loss: 0.0039
Epoch 298/500
6/6 [==============================] - 0s 335us/sample - loss: 0.0038
Epoch 299/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0037
Epoch 300/500
6/6 [==============================] - 0s 165us/sample - loss: 0.0036
Epoch 301/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0036
Epoch 302/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0035
Epoch 303/500
6/6 [==============================] - 0s 166us/sample - loss: 0.0034
Epoch 304/500
6/6 [==============================] - 0s 166us/sample - loss: 0.0033
Epoch 305/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0033
Epoch 306/500
6/6 [==============================] - 0s 167us/sample - loss: 0.0032
Epoch 307/500
6/6 [==============================] - 0s 166us/sample - loss:

Epoch 393/500
6/6 [==============================] - 0s 167us/sample - loss: 5.2793e-04
Epoch 394/500
6/6 [==============================] - 0s 167us/sample - loss: 5.1709e-04
Epoch 395/500
6/6 [==============================] - 0s 166us/sample - loss: 5.0646e-04
Epoch 396/500
6/6 [==============================] - 0s 166us/sample - loss: 4.9606e-04
Epoch 397/500
6/6 [==============================] - 0s 167us/sample - loss: 4.8587e-04
Epoch 398/500
6/6 [==============================] - 0s 0s/sample - loss: 4.7589e-04
Epoch 399/500
6/6 [==============================] - 0s 165us/sample - loss: 4.6612e-04
Epoch 400/500
6/6 [==============================] - 0s 167us/sample - loss: 4.5654e-04
Epoch 401/500
6/6 [==============================] - 0s 166us/sample - loss: 4.4716e-04
Epoch 402/500
6/6 [==============================] - 0s 166us/sample - loss: 4.3798e-04
Epoch 403/500
6/6 [==============================] - 0s 166us/sample - loss: 4.2899e-04
Epoch 404/500
6/6 [================

Epoch 487/500
6/6 [==============================] - 0s 167us/sample - loss: 7.5043e-05
Epoch 488/500
6/6 [==============================] - 0s 165us/sample - loss: 7.3502e-05
Epoch 489/500
6/6 [==============================] - 0s 167us/sample - loss: 7.1992e-05
Epoch 490/500
6/6 [==============================] - 0s 167us/sample - loss: 7.0513e-05
Epoch 491/500
6/6 [==============================] - 0s 168us/sample - loss: 6.9063e-05
Epoch 492/500
6/6 [==============================] - 0s 167us/sample - loss: 6.7645e-05
Epoch 493/500
6/6 [==============================] - 0s 166us/sample - loss: 6.6255e-05
Epoch 494/500
6/6 [==============================] - 0s 167us/sample - loss: 6.4895e-05
Epoch 495/500
6/6 [==============================] - 0s 166us/sample - loss: 6.3562e-05
Epoch 496/500
6/6 [==============================] - 0s 0s/sample - loss: 6.2256e-05
Epoch 497/500
6/6 [==============================] - 0s 0s/sample - loss: 6.0978e-05
Epoch 498/500
6/6 [===================

In [46]:
print(model.predict([10.0]))

[[18.977915]]
