In [1]:
import math
import numpy as np
import h5py
import tensorflow as tf
from tensorflow.python.framework import ops

In [6]:
def load_dataset():
    train_dataset = h5py.File('datasets/train_signs.h5', 'r')
    train_set_x_orig = np.array(train_dataset['train_set_x'][:]) # Train Set Features
    train_set_y_orig = np.array(train_dataset['train_set_y'][:]) # Train Set Labels
    
    test_dataset = h5py.File('datasets/test_signs.h5', 'r')
    test_set_x_orig = np.array(test_dataset['test_set_x'][:]) # Test Set Features
    test_set_y_orig = np.array(test_dataset['test_set_y'][:]) # Test Set Labels
    
    classes = np.array(test_dataset['list_classes'][:]) # The List of Classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

In [9]:
tf.__version__

'2.1.0'

In [19]:
# Tensorflow Basics
# Defining Tensors in TensorFlow

# 0D Tensor
d0 = tf.ones((1,))

# 1D Tensor
d1 = tf.ones((2,))


# 2D Tensor
d2 = tf.ones((2,2))


# 3D Tensor
d3 = tf.ones((2,2,2))


In [21]:
print(d0.numpy())

[1.]


In [23]:
print(d1.numpy())

[1. 1.]


In [25]:
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [27]:
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [28]:
# Defining Constants in Tensorflow
# A Constant is the simplest category of tensor
# Not Trainable
# Can have any dimension

# Define a 2*3 Constant:
a = tf.constant(3, shape=[2,3])

# Define a 2*2 Constant:
b = tf.constant([1,2,3,4], shape=[2,2])

In [30]:
print(a.numpy())

[[3 3 3]
 [3 3 3]]


In [32]:
print(b.numpy())

[[1 2]
 [3 4]]


In [33]:
# Define a Variable
a0 = tf.Variable([1,2,3,4,5,6], dtype=tf.float32)
a1 = tf.Variable([1,2,3,4,5,6], dtype=tf.int16)

In [35]:
print(a0.numpy())

[1. 2. 3. 4. 5. 6.]


In [37]:
print(a1.numpy())

[1 2 3 4 5 6]


In [38]:
# Define a Constant
b = tf.constant(2, tf.float32)

In [39]:
# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0*b

In [42]:
print(c0)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


In [44]:
print(c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


In [45]:
A = tf.ones([2,3,4])

In [54]:
A.numpy()

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [56]:
tf.reduce_sum(A, 0)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)>

In [58]:
tf.reduce_sum(A,1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>

In [59]:
tf.reduce_sum(A,2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [1]:
import tensorflow as tf

In [5]:
print(tf.version)

<module 'tensorflow_core._api.v2.version' from 'F:\\DO_NOT_TOUCH\\Anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\version\\__init__.py'>


In [6]:
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [7]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"], ["Test", "Yes"]], tf.string)

In [9]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [10]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
rank2_tensor.shape

TensorShape([2, 2])

In [22]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones

In [24]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [25]:
tensor2 = tf.reshape(tensor1, [2,3,1])

In [26]:
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [27]:
tensor3 = tf.reshape(tensor2, [3,-1])

In [28]:
tensor3.shape

TensorShape([3, 2])