In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])

In [5]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
x.shape

(5,)

In [7]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
y.shape

(3, 3)

In [9]:
y.size

9

In [10]:
string = np.array(['Hello', 'World'])
print(string)

['Hello' 'World']


In [11]:
print('Shape: ', string.shape)
print('type: ', type(string))
print('dtype:', string.dtype)

Shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype: <U5


In [12]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [15]:
x = np.array([1, 2.3, 4.5], dtype=np.int64)
print(x)
print(x.dtype)

[1 2 4]
int64


In [16]:
x = np.array([1,2,3,4,5])
np.save('my_array', x)

In [17]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


In [18]:
my_list = [1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [20]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
x = np.full((5,5), 3)

In [22]:
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [23]:
x = np.eye(5)

In [24]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(4, 9)

array([4, 5, 6, 7, 8])

In [28]:
np.arange(1,10,3)

array([1, 4, 7])

In [29]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [31]:
np.linspace(1,20,10, endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [32]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [33]:
X = np.random.random((3, 3))
print(X)

[[0.67085198 0.57460269 0.9599292 ]
 [0.30228841 0.02445701 0.80321217]
 [0.84107066 0.51534227 0.50011294]]


In [35]:
X = np.random.randint(4, 15, (3, 2))
print(X)

[[13  7]
 [ 7  9]
 [ 9  7]]


In [37]:
X = np.random.normal(0, 0.1, size=(100,100))

In [38]:
print(f"Mean: {X.mean()}")
print(f"STD: {X.std()}")
print(f"Max: {X.max()}")
print(f"Min: {X.min()}")
print(f"# Positive: {(X>0).sum()}")
print(f"# Negative: {(X<0).sum()}")

Mean: 0.00028917194795609607
STD: 0.10030159009164118
Max: 0.3417987001253986
Min: -0.40515880915771235
# Positive: 4997
# Negative: 5003


In [39]:
np.linspace(2,32,16).reshape(4,4)

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [40]:
X = [1,2,3,4,5,6]
print(X)

[1, 2, 3, 4, 5, 6]


In [41]:
X[3] = 30
print(X)

[1, 2, 3, 30, 5, 6]


In [42]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(f"Element at [0,0]: {X[0,0]}")
print(f"Element at [0,1]: {X[0,1]}")
print(f"Element at [2,2]: {X[2,2]}")

Element at [0,0]: 1
Element at [0,1]: 2
Element at [2,2]: 9


In [44]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [46]:
X = np.array([1,2,3,4,5])
print(X)
X = np.delete(X, [0,4])
print(X)

[1 2 3 4 5]
[2 3 4]


In [47]:
Y = np.arange(1, 10).reshape(3,3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n', W)

V = np.delete(Y, [0,2], axis=1)
print('\n', V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [48]:
x = np.array([1,2,3,4,5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [49]:
x = np.append(x, [7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [50]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
W = np.append(Y, [[10,11,12]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [53]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [54]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [55]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 3 4 5]


In [56]:
Y = np.arange(6).reshape(2,3)

In [57]:
print(Y)

[[0 1 2]
 [3 4 5]]


In [58]:
W = np.insert(Y, 1, [10,11,12], axis=0)

In [59]:
print(W)

[[ 0  1  2]
 [10 11 12]
 [ 3  4  5]]


In [60]:
V = np.insert(Y, 1, 5, axis=1)
print(V)

[[0 5 1 2]
 [3 5 4 5]]


In [61]:
X = np.array([1,2])
print(X)

[1 2]


In [62]:
Y = np.array([[3,4], [5,6]])
print(Y)

[[3 4]
 [5 6]]


In [63]:
np.vstack((X,Y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
np.hstack((Y, X.reshape(2,1)))

array([[3, 4, 1],
       [5, 6, 2]])