In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.shape

(5,)

In [5]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
y.shape

(3, 3)

In [7]:
y.size

9

In [8]:
string = np.array(['Hello', 'World'])
print(string)

['Hello' 'World']


In [9]:
print('Shape: ', string.shape)
print('type: ', type(string))
print('dtype:', string.dtype)

Shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype: <U5


In [10]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [11]:
x = np.array([1, 2.3, 4.5], dtype=np.int64)
print(x)
print(x.dtype)

[1 2 4]
int64


In [12]:
x = np.array([1,2,3,4,5])
np.save('my_array', x)

In [13]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


In [14]:
my_list = [1,2,3,4]
np.array(my_list)

array([1, 2, 3, 4])

In [15]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
x = np.full((5,5), 3)

In [17]:
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [18]:
x = np.eye(5)

In [19]:
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(4, 9)

array([4, 5, 6, 7, 8])

In [23]:
np.arange(1,10,3)

array([1, 4, 7])

In [24]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [25]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [26]:
np.linspace(1,20,10, endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [27]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [28]:
X = np.random.random((3, 3))
print(X)

[[0.25752086 0.9326061  0.48285473]
 [0.11941051 0.10963071 0.03379404]
 [0.62322202 0.42464754 0.56213463]]


In [29]:
X = np.random.randint(4, 15, (3, 2))
print(X)

[[ 7 12]
 [14  5]
 [12 10]]


In [30]:
X = np.random.normal(0, 0.1, size=(100,100))

In [31]:
print(f"Mean: {X.mean()}")
print(f"STD: {X.std()}")
print(f"Max: {X.max()}")
print(f"Min: {X.min()}")
print(f"# Positive: {(X>0).sum()}")
print(f"# Negative: {(X<0).sum()}")

Mean: 0.0007898221225364276
STD: 0.09997159146166819
Max: 0.38017977752571486
Min: -0.42508254250231536
# Positive: 5002
# Negative: 4998


In [32]:
np.linspace(2,32,16).reshape(4,4)

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [33]:
X = [1,2,3,4,5,6]
print(X)

[1, 2, 3, 4, 5, 6]


In [34]:
X[3] = 30
print(X)

[1, 2, 3, 30, 5, 6]


In [35]:
X = np.arange(1, 10).reshape(3, 3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(f"Element at [0,0]: {X[0,0]}")
print(f"Element at [0,1]: {X[0,1]}")
print(f"Element at [2,2]: {X[2,2]}")

Element at [0,0]: 1
Element at [0,1]: 2
Element at [2,2]: 9


In [37]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [38]:
X = np.array([1,2,3,4,5])
print(X)
X = np.delete(X, [0,4])
print(X)

[1 2 3 4 5]
[2 3 4]


In [39]:
Y = np.arange(1, 10).reshape(3,3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n', W)

V = np.delete(Y, [0,2], axis=1)
print('\n', V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [40]:
x = np.array([1,2,3,4,5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [41]:
x = np.append(x, [7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [42]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
W = np.append(Y, [[10,11,12]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [45]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [46]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 3 4 5]


In [47]:
Y = np.arange(6).reshape(2,3)

In [48]:
print(Y)

[[0 1 2]
 [3 4 5]]


In [49]:
W = np.insert(Y, 1, [10,11,12], axis=0)

In [50]:
print(W)

[[ 0  1  2]
 [10 11 12]
 [ 3  4  5]]


In [51]:
V = np.insert(Y, 1, 5, axis=1)
print(V)

[[0 5 1 2]
 [3 5 4 5]]


In [52]:
X = np.array([1,2])
print(X)

[1 2]


In [53]:
Y = np.array([[3,4], [5,6]])
print(Y)

[[3 4]
 [5 6]]


In [54]:
np.vstack((X,Y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.hstack((Y, X.reshape(2,1)))

array([[3, 4, 1],
       [5, 6, 2]])

In [56]:
X = np.arange(1,21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [57]:
z = X[1:4,2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [58]:
X[:,2]

array([ 3,  8, 13, 18])

In [59]:
X[:,2:3]

array([[ 3],
       [ 8],
       [13],
       [18]])

In [60]:
z = X[1:, 2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [61]:
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [62]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [63]:
indices = np.array([1,3])
print(indices)

[1 3]


In [64]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [65]:
y = X[indices, :]
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [66]:
np.diag(X)

array([ 1,  7, 13, 19])

In [67]:
np.diag(X, k=1)

array([ 2,  8, 14, 20])

In [68]:
np.diag(X, k=-1)

array([ 6, 12, 18])

In [69]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [70]:
X[X > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [71]:
X[X<17]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [72]:
X[(X>5) & (X<17)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [73]:
X[(X>5) & (X<17)] = 1

In [74]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,9,10])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2]
[1 3 4 5]
[ 1  2  3  4  5  6  7  9 10]


In [76]:
x = np.random.randint(1,11,size=(10,))
x

array([10,  7,  1,  9,  6,  8,  5,  5,  1,  9])

In [77]:
print(np.sort(x))

[ 1  1  5  5  6  7  8  9  9 10]


In [78]:
print(np.sort(np.unique(x)))

[ 1  5  6  7  8  9 10]


In [79]:
x.sort()
print(x)

[ 1  1  5  5  6  7  8  9  9 10]


In [80]:
X = np.random.randint(1,11, size=(5,5))
print(X)

[[ 7  9  4  1  6]
 [ 8  9  8  3  6]
 [ 4  5  5 10  8]
 [ 7 10 10  2  9]
 [ 8  6  1  2  7]]


In [81]:
print(np.sort(X, axis=0))

[[ 4  5  1  1  6]
 [ 7  6  4  2  6]
 [ 7  9  5  2  7]
 [ 8  9  8  3  8]
 [ 8 10 10 10  9]]


In [82]:
X

array([[ 7,  9,  4,  1,  6],
       [ 8,  9,  8,  3,  6],
       [ 4,  5,  5, 10,  8],
       [ 7, 10, 10,  2,  9],
       [ 8,  6,  1,  2,  7]])

In [83]:
print(np.sort(X, axis=1))

[[ 1  4  6  7  9]
 [ 3  6  8  8  9]
 [ 4  5  5  8 10]
 [ 2  7  9 10 10]
 [ 1  2  6  7  8]]


In [84]:
X = np.arange(1,26).reshape(5,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [85]:
X[X%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [86]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [87]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [88]:
X = np.arange(0, 12).reshape(3,4)

In [89]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
print(X.sum())

66


In [91]:
X.sum(axis=0)

array([12, 15, 18, 21])

In [92]:
X.sum(axis=1)

array([ 6, 22, 38])

In [93]:
X.max()

11

In [94]:
X.min()

0

In [95]:
X + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [96]:
X - 3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [97]:
X * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [98]:
X = np.arange(9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [99]:
Y = np.arange(3)
print(Y)

[0 1 2]


In [100]:
X + Y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [101]:
X = np.ones((4,4), dtype=int) * np.arange(1,5)

In [102]:
X

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [103]:
import numpy as np

In [104]:
X = np.random.randint(0,5001, size=(1000,20))

print(X.shape)

(1000, 20)


In [105]:
avg_col = np.mean(X, axis=0)

### Mean Normalization
<br/>
<div align='justify'>In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is normalized in order to work correctly. The idea of normalization, also known as feature scaling, is to ensure that all the data is on a similar scale, i.e. that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.</div>
<br/>
<div align='justify'>In this lab, you will be performing a different kind of feature scaling known as mean normalization. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform mean normalization your data will not only be scaled but it will also have an average of zero.</div>

In [108]:
X

array([[ 398,  520, 3312, ...,  200, 3355, 3763],
       [ 368, 1492, 2687, ..., 4458,  862,  564],
       [1504, 4679, 4313, ..., 2189,  751, 2127],
       ...,
       [  68, 3459, 2779, ..., 3705,  563, 2581],
       [2098, 3983, 1374, ..., 1877, 3155, 4789],
       [4111, 2337, 1557, ..., 4894, 2533,  780]])

In [107]:
# Average of the values in each column of X
avg_cols = np.mean(X, axis=0)

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

In [110]:
avg_cols

array([2500.067, 2549.085, 2437.371, 2533.092, 2500.788, 2527.692,
       2504.393, 2521.452, 2484.461, 2587.858, 2450.425, 2453.147,
       2535.111, 2510.141, 2412.587, 2632.258, 2445.62 , 2504.03 ,
       2447.637, 2512.858])

In [109]:
std_cols

array([1429.80088841, 1490.23916932, 1427.38214202, 1384.42750967,
       1440.80388709, 1468.99310588, 1441.9940085 , 1443.93510578,
       1451.07078824, 1490.46585531, 1446.55692469, 1466.13785825,
       1461.95956602, 1438.31500066, 1436.46809099, 1428.9000145 ,
       1445.16320656, 1450.92335397, 1477.66342082, 1459.40820329])

In [111]:
print(avg_cols.shape)
print(std_cols.shape)

(20,)
(20,)


In [112]:
X_norm = (X-avg_cols) / std_cols

In [113]:
print(np.mean(X_norm))

-2.6467716907063732e-17


In [114]:
print(np.mean(X_norm.min()))

-1.8407572071596148


In [115]:
X_norm.min()

-1.8407572071596148

In [118]:
np.random.permutation(5)

array([3, 4, 2, 0, 1])

In [119]:
row, column = X_norm.shape
row_indices = np.random.permutation(row)

In [120]:
X_train = X_norm[row_indices[:600]] # training set

X_crossVal = X_norm[row_indices[600:800]] # Cross Validation Set

X_test = X_norm[row_indices[800:1000]] # Test Set

In [121]:
print(X_train.shape)

(600, 20)


In [122]:
X_crossVal.shape

(200, 20)

In [123]:
X_test.shape

(200, 20)