### The Keras Functional API

In [1]:
from tensorflow.keras.layers import Input, Dense, Flatten, Conv1D, AveragePooling1D
from tensorflow.keras.models import Model

In [3]:
inputs = Input(shape=(32,1))
h = Conv1D(16, 5, activation='relu')(inputs)
h = AveragePooling1D(3)(h)
h = Flatten()(h)
outputs = Dense(20, activation='sigmoid')(h)

model = Model(inputs=inputs, outputs=outputs)

### Variables to Numpy

In [4]:
import tensorflow as tf

In [7]:
my_var = tf.Variable([-1,2], dtype=tf.float32, name='my_var')
my_var

<tf.Variable 'my_var:0' shape=(2,) dtype=float32, numpy=array([-1.,  2.], dtype=float32)>

In [8]:
my_var.assign([3.5, -2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([ 3.5, -2. ], dtype=float32)>

In [9]:
X = my_var.numpy()
print(X)

[ 3.5 -2. ]


### Tensors and Variables

In [10]:
import numpy as np

In [11]:
strings = tf.Variable(['Hello World!'], tf.string)
floats = tf.Variable([3.12, 2.71], tf.float64)
ints = tf.Variable([2,3,4], tf.int32)
complexes = tf.Variable([2 - 3j, 1.23 - 4.91j], tf.complex128)

In [13]:
# Initialize a Variable Value
tf.Variable(tf.constant(4.2, shape=(3,3)))

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]], dtype=float32)>

In [14]:
# Create a Constant Tensor
x = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(f'dtype: {x.dtype}')
print(f'shape: {x.shape}')

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
dtype: <dtype: 'int32'>
shape: (3, 3)


In [15]:
coefs = np.arange(16)

In [16]:
shape1 = [8, 2]
shape2 = [4, 4]
shape3 = [2,2,2,2]

In [17]:
a = tf.constant(coefs, shape=shape1)
print(a)

b = tf.constant(coefs, shape=shape2)
print(b)

c = tf.constant(coefs, shape=shape3)
print(c)

tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]], shape=(8, 2), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]], shape=(2, 2, 2, 2), dtype=int32)


In [18]:
# Create a Constant layer
t = tf.constant(np.arange(80), shape=[5,2,8])

In [19]:
# Get the rank of a Tensor
rank = tf.rank(t)
rank

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
# Reshape
t2 = tf.reshape(t, [8, 10])
print(t2)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]], shape=(8, 10), dtype=int32)


In [21]:
ones = tf.ones(shape=(2,3))
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
t1 = tf.ones(shape=(2,2))
t2 = tf.zeros(shape=(2,2))

In [23]:
concat0 = tf.concat([t1, t2], 0)
concat1 = tf.concat([t1, t2], 1)

In [25]:
print(concat0)
print(concat1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [26]:
t = tf.constant(np.arange(24), shape=[3,2,4])
t.shape

TensorShape([3, 2, 4])

In [27]:
t1 = tf.expand_dims(t, 0)
t2 = tf.expand_dims(t, 3)
t2.shape

TensorShape([3, 2, 4, 1])

In [28]:
t2 = tf.squeeze(t2, 3)
t2.shape

TensorShape([3, 2, 4])